create table department(
    dept_id VARCHAR2(50) NOT NULL,
    dept_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(dept_id)
);



create table designation(
    designation_id NUMBER NOT NULL,
    designation_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(designation_id)
);


create table hrms_employee_details(
    emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    middle_nam e VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    designation_id NUMBER(15) NOT NULL,
    dept_id  VARCHAR2(50) NOT NULL,
    birthdate DATE NOT NULL,
    sex VARCHAR2(10) NOT NULL,
    houseno NUMBER(15) NOT NULL,
    street_name VARCHAR2(50) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    pincode NUMBER(15) NOT NULL,
    employment_date DATE NOT NULL,
    reporting_manager VARCHAR2(50) NOT NULL,
    PRIMARY KEY(emp_id),
   CONSTRAINT FK_DEPT FOREIGN KEY (dept_id) REFERENCES DEPARTMENT(dept_id),
   CONSTRAINT FK_DESIGNATION FOREIGN KEY (designation_id) REFERENCES DESIGNATION(designation_id)
);

create table hrms_employee_projects(
    project_id VARCHAR2(10) NOT NULL,
    emp_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    project_startdate DATE NOT NULL,
    project_ENDdate DATE NOT NULL,
    project_status VARCHAR2(30) NOT NULL,
    PRIMARY KEY(project_id),
    CONSTRAINT FK_employeedetails FOREIGN KEY (emp_id) REFERENCES hrms_employee_details(emp_id)
);

create table hrms_employee_salary(
    emp_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    lower_salaryrange VARCHAR2(30) NOT NULL,
    higher_salaryrange VARCHAR2(30) NOT NULL,
    annual_income NUMBER NOT NULL,
    taxable VARCHAR2(30) NOT NULL,
    loans VARCHAR2(30) NOT NULL,
    insurance VARCHAR2(30) NOT NULL,
    CONSTRAINT FK_empid FOREIGN KEY (emp_id) REFERENCES hrms_employee_details(emp_id)
);

create table hrms_employee_trainings(
    training_id NUMBER NOT NULL,
    emp_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    skills VARCHAR2(100) NOT NULL,
    trainings_completed VARCHAR2(100) NOT NULL,
    annual_income NUMBER NOT NULL,
    taxable VARCHAR2(30) NOT NULL,
    loans VARCHAR2(30) NOT NULL,
    insurance VARCHAR2(30) NOT NULL,
    CONSTRAINT empid FOREIGN KEY (emp_id) REFERENCES hrms_employee_details(emp_id)
);

create table skills(
    skill_id NUMBER NOT NULL,
    skill_name VARCHAR2(100) NOT NULL,
    skill_level VARCHAR2(100) NOT NULL,
    PRIMARY KEY(skill_id)
);



create table hrms_employee_leaves(
    leave_id NUMBER NOT NULL,
    emp_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    leave_startdate DATE NOT NULL,
    leave_enddate DATE NOT NULL,
    total_days NUMBER NOT NULL,
    leavetype VARCHAR2(30) NOT NULL,
    PRIMARY KEY(leave_id),
    CONSTRAINT employeeid FOREIGN KEY (emp_id) REFERENCES hrms_employee_details(emp_id)
);

create table hrms_employee_attendance(
    attendance_id NUMBER NOT NULL,
    emp_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    time_in TIMESTAMP NOT NULL,
    time_out TIMESTAMP NOT NULL,
    remarks VARCHAR2(100) NOT NULL,
    PRIMARY KEY(attendance_id),
    CONSTRAINT employid FOREIGN KEY (emp_id) REFERENCES hrms_employee_details(emp_id)
);

create table asset(
    asset_id NUMBER NOT NULL,
    emp_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    asset_name VARCHAR2(100) NOT NULL,
    asset_type VARCHAR2(100) NOT NULL,
    asset_details VARCHAR2(100) NOT NULL,
    creation_date DATE NOT NULL,
    PRIMARY KEY(asset_id),
    CONSTRAINT employeid FOREIGN KEY (emp_id) REFERENCES hrms_employee_details(emp_id)
);
