insert into DEPARTMENT (dept_id, dept_name) values (10, 'Research and Development');
insert into DEPARTMENT (dept_id, dept_name) values (20, 'Sales');
insert into DEPARTMENT (dept_id, dept_name) values (30, 'Human Resources');
insert into DEPARTMENT (dept_id, dept_name) values (40, 'Accounting');
insert into DEPARTMENT (dept_id, dept_name) values (50, 'Marketing');
insert into DEPARTMENT (dept_id, dept_name) values (60, 'Finanace');
insert into DEPARTMENT (dept_id, dept_name) values (70, 'Operations');
insert into DEPARTMENT (dept_id, dept_name) values (80, 'Production');


insert into designation (designation_id, designation_name) values (101, 'VP Accounting');
insert into designation (designation_id, designation_name) values (102, 'Design Engineer');
insert into designation (designation_id, designation_name) values (103, 'Senior Developer');
insert into designation (designation_id, designation_name) values (104, 'Software Engineer');
insert into designation (designation_id, designation_name) values (105, 'Media Manager');
insert into designation (designation_id, designation_name) values (106, 'Automation Specialist');
insert into designation (designation_id, designation_name) values (107, 'Project Manager');
insert into designation (designation_id, designation_name) values (108, 'Help Desk Operator');

insert into projects (project_id, project_name) values ('A1', 'Batman');
insert into projects (project_id, project_name) values ('A2', 'Bender Project');
insert into projects (project_id, project_name) values ('A21', 'Canary');
insert into projects (project_id, project_name) values ('A3', 'Casanova');
insert into projects (project_id, project_name) values ('A5', 'Cascade');
insert into projects (project_id, project_name) values ('A7', 'Bigfish');
insert into projects (project_id, project_name) values ('A8', 'Bigfoot');
insert into projects (project_id, project_name) values ('A9', 'HornedFrogs');
insert into projects (project_id, project_name) values ('FN1', 'Hornets');
insert into projects (project_id, project_name) values ('FN2', 'Husky Cat');
insert into projects (project_id, project_name) values ('FN3', 'Massive Monkeys');
insert into projects (project_id, project_name) values ('FN4', 'Matadors');
insert into projects (project_id, project_name) values ('FN5', 'Mercury');
insert into projects (project_id, project_name) values ('FN6', 'Bomb Squad');
insert into projects (project_id, project_name) values ('FN7', 'Violent Storms');
insert into projects (project_id, project_name) values ('FN8', 'Weekend Warriors');
insert into projects (project_id, project_name) values ('FN9', 'Westeners');
insert into projects (project_id, project_name) values ('O1', 'Fast Balls');
insert into projects (project_id, project_name) values ('O2', 'Next Gala');
insert into projects (project_id, project_name) values ('O22', 'FNP');
insert into projects (project_id, project_name) values ('O3', 'element Fleet');
insert into projects (project_id, project_name) values ('O4', 'Alexa');
insert into projects (project_id, project_name) values ('O5', 'Hotel management system');
insert into projects (project_id, project_name) values ('O6', 'Blueman');
insert into projects (project_id, project_name) values ('O7', 'Delivery system');
insert into projects (project_id, project_name) values ('O8', 'Snell');
insert into projects (project_id, project_name) values ('O9', 'Trumph');
insert into projects (project_id, project_name) values ('P3', 'code honors');
insert into projects (project_id, project_name) values ('P4', 'Charles');
insert into projects (project_id, project_name) values ('P5', 'Blue Bird');
insert into projects (project_id, project_name) values ('P6', 'Network');
insert into projects (project_id, project_name) values ('P7', 'Passion Chaser');
insert into projects (project_id, project_name) values ('P9', 'Orange Leader');
insert into projects (project_id, project_name) values ('RD1', 'Yaeger');
insert into projects (project_id, project_name) values ('RD10', 'Yellow Moose');
insert into projects (project_id, project_name) values ('RD2', 'Yosmita');
insert into projects (project_id, project_name) values ('RD3', 'Sirius');
insert into projects (project_id, project_name) values ('RD5', 'Soul Spartrans');
insert into projects (project_id, project_name) values ('RD6', 'Red Butter');
insert into projects (project_id, project_name) values ('RD7', 'Sputnik');
insert into projects (project_id, project_name) values ('RD8', 'Rhinestone');

insert into asset (asset_Id, asset_name, asset_type) values (8001, 'Laptop', 'Electronics');
insert into asset (asset_Id, asset_name, asset_type) values (8002, 'Desktop', 'Electronics');
insert into asset (asset_Id, asset_name, asset_type) values (8003, 'KeyBoard', 'Electronics');
insert into asset (asset_Id, asset_name, asset_type) values (8004, 'Mouse', 'Electronics');
insert into asset (asset_Id, asset_name, asset_type) values (8005, 'Projector', 'Accessories');
insert into asset (asset_Id, asset_name, asset_type) values (8006, 'SpikeGuard', 'Accessories');
insert into asset (asset_Id, asset_name, asset_type) values (8007, 'Speakers', 'Accessories');
insert into asset (asset_Id, asset_name, asset_type) values (8008, 'HeadPhones', 'Accessories');

insert into skills (skill_id, skill_name, skill_level) values (6001, 'Signal Processing','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6002, 'Talent Management','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6003, 'Fine Dining','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6004, 'DMX','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6005, 'Loans','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6006, 'Custom CMS Development','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6007, 'EJB','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6008, 'DSM-IV','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6009, 'Whole Life','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6010, 'Overhaul','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6011, 'Dynamics','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6012, 'HP Service Manager','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6013, 'Data Management','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6014, 'RPM','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6015, 'Kundalini','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6016, 'PTF','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6017, 'New Urbanism','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6018, 'Drywall','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6019, 'Ebooks','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6020, 'Justice','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6021, 'Export','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6022, 'Phone Etiquette','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6023, 'Guided Imagery','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6024, 'NRA','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6025, 'Art','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6026, 'Zeolites','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6027, 'FrameMaker','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6028, 'Financial Risk Management','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6029, 'DSLAM','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6030, 'Zumba Instruction','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6031, 'Thermodynamics','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6032, 'VSTO','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6033, 'Twilio','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6034, 'Rhythm Guitar','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6035, 'MPBN','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6036, 'dSPACE','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6037, 'Kodaly','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6038, 'VSOE','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6039, 'FCNSA','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6040, 'RDL','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6041, 'AHWD','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6042, 'PDS','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6043, 'Kaledo','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6044, 'Orchestral Music','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6045, 'Gnome','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6046, 'XRY','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6047, 'Local Government','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6048, 'RMS','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6049, 'RAN','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6050, 'Middle Eastern Studies','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6051, 'Corporate Finance','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6052, 'Luxury','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6053, 'Ignatian Spirituality','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6054, 'JMX','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6055, 'PTH','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6056, 'Jimmy Jib','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6057, 'E-commerce','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6058, 'Vulnerability Research','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6059, 'Long-term Care','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6060, 'AV Integration','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6061, 'Analytical Ultracentrifugation','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6062, 'Fiction Writing','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6063, 'E-on Vue','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6064, 'HMDA','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6065, 'GWT','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6066, 'Budgeting','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6067, 'ABAP Web Dynpro','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6068, 'Two-phase Flow','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6069, 'UCINET','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6070, 'JNCIP','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6071, 'Subversion','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6072, 'MRO Management','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6073, 'Wind Turbines','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6074, 'Navisworks','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6075, 'ATM Networks','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6076, 'VBA','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6077, 'Smart TV','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6078, 'Emergency Nursing','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6079, 'Statistical Data Analysis','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6080, 'Classroom','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6081, 'DMS-100','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6082, 'HSEQ','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6083, 'Easytrieve','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6084, 'LLDPE','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6085, 'Hypertension','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6086, 'Phase II ESA','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6087, 'Oscilloscope','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6088, 'Business Development','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6089, 'XSL','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6090, 'Hospital Sales','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6091, 'VTK','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6092, 'BPL','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6093, 'CBT','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6094, 'Strategic HR','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6095, 'Personal Development','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6096, 'Lync','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6097, 'MSP Practitioner','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6098, 'WHIMS','Beginner');
insert into skills (skill_id, skill_name, skill_level) values (6099, 'Corporate Real Estate','Intermediate');
insert into skills (skill_id, skill_name, skill_level) values (6100, 'Sales','Intermediate');

insert into wages (wage_Id, designation_id, wages) values (5001, 101, 50);
insert into wages (wage_Id, designation_id, wages) values (5002, 102, 45);
insert into wages (wage_Id, designation_id, wages) values (5003, 103, 48);
insert into wages (wage_Id, designation_id, wages) values (5004, 104, 40);
insert into wages (wage_Id, designation_id, wages) values (5005, 105, 35);
insert into wages (wage_Id, designation_id, wages) values (5006, 106, 45);
insert into wages (wage_Id, designation_id, wages) values (5007, 107, 40);
insert into wages (wage_Id, designation_id, wages) values (5008, 108, 30);
